name: Проверка и сборка

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Установка зависимостей
        run: |
          pip install ursina
          pip install pyinstaller
      
      - name: Проверка кода
        run: python -m py_compile game.py
      
      - name: Сборка EXE
        run: |
          pyinstaller --onefile --windowed --collect-data ursina --name "МояИгра" D.py
      
      - name: Загрузка EXE
        uses: actions/upload-artifact@v3
        with:
          name: MyGame-EXE
          path: dist/*.exe
